### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by tomdeblende** [xen0l/aws-gate#10]
Dear,

I can connect to an instance using this command for MFA and profile usage:

aws-gate session server1 --profile profile1

However, I get prompted for my MFA token twice when using the Name tag, not when using instance ID. And they need to be different. Which is a pain. How can this be solved?

Thanks,
Tom

**Comment by xen0l** [comment]
Hey @tomdeblende,

sorry for late response. Asking for MFA when using Name tag, but not asking when using instance ID is weird. By any chance do you have different configuration for default and profile1?

aws-gate will ask for MFA every time we are contacting AWS API. Internally, I am doing multiple call to convert and fetch instance ID. If you want to get rid of multiple MFA prompts, i can recommend using aws-vault. Hopefully, this answer was helpful.
