### ISSUE TITLE
"Invalid profile provided: default" when using environment variables

### ISSUE THREAD

**Issue by ikben** [xen0l/aws-gate#109]
I'm using environment variables to configure the AWS credentials for aws-gate and don't have a default profile in .aws/config because of that. (I'm using https://github.com/99designs/aws-vault (eg `aws-vault exec profile_name -- aws-gate list`), but any tool that sets environment variables will work the same).

This leads to the error "Invalid profile provided: default" when running aws-gate (even though valid credentials are available in the environment). I can work around this by adding a dummy default profile in the configuration file, but it would be nice if that wasn't needed.

**Comment by xen0l** [comment]
@ikben thanks for reporting, I will have a look in the upcoming days!
