### ISSUE TITLE
when using mfa, OTP code needs to be entered twice

### ISSUE THREAD

**Issue by becrsh** [xen0l/aws-gate#316]
Hi,

Found your tool and it would cover our use case perfectly. but we are using mfa and every request triggers a new session creation (and also a new mfa request). In this case we need to enter 2 codes to do an ls or a session. 

Created a pull request that would solve this by adding the credential cache to it (and pointing it to the same as the cli)

**Comment by xen0l** [comment]
Hey @becrsh,

thanks for your contribution. I am also glad to hear that aws-gate fits you need. I will have a look at your PR in the upcoming days.

**Comment by xen0l** [comment]
Will be released in 0.8.8, thanks for contribution!
