### ISSUE TITLE
Support AWS-StartInteractiveCommand

### ISSUE THREAD

**Issue by nc-furstenauw** [xen0l/aws-gate#356]
If this falls under the scope of #256 then feel free to close it, but this feature would allow me to let my developers open consoles for whatever language they're using, instead of forcing them to navigate the instance filesystem to whatever application they are working on. It also would allow a user to use whatever shell they wanted by default, while still providing the logging that the SSH sessions don't provide. I might take a stab at creating a PR for this myself, but I wanted to let you know that the desire for this existed.

**Comment by xen0l** [comment]
Hello @nc-furstenauw,

thanks for the idea. Could you provide some example how you run this via aws cli just to verify we are thinking about the same thing? Do you have exactly [this](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html#sessions-start-interactive-commands) in mind?

My idea for #256 was basically to be able to execute specific commands that would be defined in documents following that. I wanted to provide an interface on top of it in a new subcommand:

`aws-gate run host document_alias`

where document_alias would be defined in the configuration file. This would provide a user friendly way for user to create much more readable commands than just passing document names, e.g.

`aws-gate run backend make_thread_dump`

Then in `~/.aws-gate/config` if would look at a section (e.g. custom_commands) and get the document name from that. 

What do you think about this interface?

**Comment by xen0l** [comment]
However, looking at `AWS-StartInteractiveCommand`, if I understand correctly, it takes {{command}} as argument and option to run the command as root. For this, I could imagine implementing `aws-gate exec host command` (with option `--elevated` to activate root user level permissions). If so, this shouldn't be difficult to implement.

**Comment by nc-furstenauw** [comment]
Yeah, the example you have in the second comment would be perfect. In awscli terms what I'd like would look something like `aws ssm start-session --target ${host} --document-name AWS-StartInteractiveCommand --parameters command="bash -l"`. I'd like to do something like 'sudo su -c "cd; be rails c env" - user', but I currently can't get that to work for the cli & the documentation for this is fairly sparse, and I already have other ideas to get around that with what I do have working.

So something like `aws-gate exec host command` would be perfect

**Comment by xen0l** [comment]
@nc-furstenauw there is #374 open, let me know your feedback.

**Comment by nc-furstenauw** [comment]
@xen0l yep it seems to be working exactly as expected! Might want to make a note in the documentation that the command (or commands) should be wrapped in double quotes, at least that's what I needed to do to get it to work for me

**Comment by xen0l** [comment]
Uhm, I am not sure about the double quotes. I tested it today without just like `aws-gate exec <hostname> bash -l`. What command did you run exactly? Once this is figured out, I will add tests and documentaiton and merge.

**Comment by xen0l** [comment]
@nc-furstenauw merged and released in 0.9.0. if you see any issues, please report issues.
