### ISSUE TITLE
Dependency on PyYAML==5.1.2 breaks compatibility with awscli

### ISSUE THREAD

**Issue by jwarlander** [xen0l/aws-gate#38]
Currently it seems that `awscli` depends on `PyYAML<=5.1` for Python 3, which means that trying to install `aws-gate` AND `awscli` in the same Python environment doesn't work without a manual override.

Perhaps `aws-gate` should have a relaxed dependency, like eg. `PyYAML>=5.1,<5.2` or whatever makes sense for the actual features used?

_**NOTE:** There is a PR for `awscli` to bump the PyYAML dependency (https://github.com/aws/aws-cli/pull/4355), but it's not there now, and it's so far unclear if it will actually solve this, as right now the aim is 5.1.1, not 5.1.2._

**Comment by xen0l** [comment]
Hello @jwarlander, thanks for reporting this. I was playing around with dependabot and I thought it be working. I am fine with the proposed solution (`PyYAML>=5.1,<5.2`) as it will fix the issue for you. Do you think that you can create a PR?

BTW, what platform are you using? I am currently testing homebrew package for aws-gate, which will allow to install aws-gate via homebrew. However, I ran into some issues, which I am trying to work on.

**Comment by xen0l** [comment]
Issues fixed in 0.4.1.

**Comment by jwarlander** [comment]
Thanks for the quick fix!

I'm on Linux (Ubuntu). Would definitely be cool if there was a .deb package available, or even, say, a PPA on https://launchpad.net/ -- but I can appreciate if you don't feel the effort is warranted, since `pip` installations tend to work fairly well.
