### ISSUE TITLE
eu connectivity fails via KMS

### ISSUE THREAD

**Issue by jonassteinberg1** [xen0l/aws-gate#689]
Hi, xen0l.  Love the tool, use it constantly.  Not sure what AWS changed network side, but eu connections are failing KMS handshakes.  Pretty straightforward:

```
# aws-gate version

Package          Version
---------------- ---------
aws-gate         0.9.3

# eu-central-1

> aws-gate session bastioneu
Starting session with SessionId: me@work-some-session-id
SessionId: me@work-some-session-id:
----------ERROR-------
Encountered error while initiating handshake. Handshake timed out. Please ensure that you have the latest version of the session manager plugin.

# us-east-1
> aws-gate session bastion

Starting session with SessionId: me@work-some-session-id
sh-4.2$ exit
Exiting session with sessionId: me@work-some-session-id


# eu via awscli
> aws ssm start-session --target some-instance-id --profile eu --region eu-central-1

Starting session with SessionId: me@work-some-session-id
This session is encrypted using AWS KMS.
sh-4.2$ exit
Exiting session with sessionId: me@work-some-session-id
```

**Comment by xen0l** [comment]
Hey,

that's weird. Can you post console output from `aws-gate session` from both sessions (us-east-1 and eu-central-1) with `GATE_DEBUG=1` environment variable set (more [info](https://aws-gate.readthedocs.io/en/latest/development/#debug-mode))? It will provide debug information (you should remove possibly sensitive things, e.g. account id, profile name, instance IDs, PII etc) and that will shed more light on the problem.
