### ISSUE TITLE
Distribute .exe file of aws-gate on Windows

### ISSUE THREAD

**Issue by mbp** [xen0l/aws-gate#728]
My other "pip installed" tools that are installed into `%USERPROFILE%\AppData\local\Programs\Python\Python39\Scripts` are `.exe` files that can then easily be invoked on command line.

However in this directory `aws-gate` is just a script file (no extension), with following content:

```
#!c:\users\xxx\appdata\local\programs\python\python39\python.exe

import aws_gate.cli


def main():
    aws_gate.cli.main()


if __name__ == '__main__':
    main()
```

Because it is not an executable, you have to run it with `py aws-gate` and to be in the same directory as the script. This makes it a bit harder to use.

One example of another tool that installs an exe is: https://github.com/mludvig/aws-ssm-tools - maybe it can be used for inspiration.

**Comment by xen0l** [comment]
@mbp binaries will be automaticlly on every new release and uploaded on the release page. Few binaries are available here: https://github.com/xen0l/aws-gate/releases/tag/0.11.1. I will releasae a new version, so github releases and PyPI versions are in sync. **Please note, that these binaries do not need Python installed, everything is contained in the binary itself (hence the size).**

Plesae note even though we produce binaries for macOS and Linux, they might not work on all the platform and on those platforrms, Homebrew and pip are the recommended way how to install them. Self-contained binaries are mostly useful on Windows. 

Next steps:
* new 0.11.2 release
* provide documentation about these binaries
* @mbp once available, could you provide docs how to install aws-gate into Windows path?
