### ISSUE TITLE
does not support windows

### ISSUE THREAD

**Issue by Rayanearaujo** [xen0l/aws-gate#934]
I have tried to run it on windows but it does not work. The installation process using pip works perfectly but once installed it does not work once pip only stall the package and no binary for windows is installed. So I tried to download the binary from [here](https://github.com/xen0l/aws-gate/releases) but it did not work either. When trying to execute `aws-gate bootstrap -f` I received the message `Failed to execute script aws-gate`.

**Comment by xen0l** [comment]
It fails because we don't support downloading SSM plugin from AWS via this mechanism on Windows. This is not a bug as the functionality is not supported. Also, I have limited options to test it as I have no access to Windows machine.
